Add netstandard2.1 target to NuGet.Services.Cursor/Storage
NuGet/ServerCommon pull request #399
Opened 2022-07-14 05:41 UTC by drewgillies

This is to provide storage (and possibly cursor) services to this work: https://github.com/NuGet/Engineering/issues/4439

2022-07-14 16:40 UTC, joelverhagen commented on src/NuGet.Services.Storage/AzureStorage.cs
> +#if NETFRAMEWORK
Can we just make `NETFRAMEWORK` use the async flow here? Seems to me that the risk is low.

2022-07-14 16:40 UTC, joelverhagen commented on src/NuGet.Services.Storage/AzureStorage.cs
> +#if NETFRAMEWORK
Same as above, can this be async for both targets?

2022-07-14 16:43 UTC, joelverhagen commented on src/NuGet.Services.Storage/AzureStorage.cs
> +                Task.Run(() => _directory.Container.SetPermissionsAsync(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob })).Wait();  // the framework code blocks the
Why `Task.Run` instead of just `Wait()` on the task returned by `SetPermissionsAsync`?

Also, for all of the places where there's a mix of sync and async, can we introduce a async, private, helper function that we just block on in the sync version?

2022-07-14 16:48 UTC, joelverhagen commented on src/NuGet.Services.Storage/AzureStorage.cs
> +            if (initializeContainer && _directory.Container.CreateIfNotExistsAsync().Result) // the framework code blocks the thread similarly
Can this logic be moved to a lazy method? e.g. a `Lazy<Task<...>` field that runs this initialization code exactly once upon the first method invocation? Also can we as async versions of all of the methods so we don't need to do "sync over async" (which has problems: https://stackoverflow.com/a/24298425)

This could move us in the right direction where we a) don't do hard work in the constructor and b) have async methods for all async dependencies.

It's possible we'll run into deadlock situations with sync over async depending on our runtime.

2022-07-14 16:48 UTC, joelverhagen commented on src/NuGet.Services.Storage/AzureStorage.cs
> +            if (initializeContainer && _directory.Container.CreateIfNotExistsAsync().Result) // the framework code blocks the thread similarly
If it's both too expensive to refactor like this and we don't run into any problems with sync over async, then I understand taking the shortcut, but it's really not ideal.

2022-07-14 16:49 UTC, joelverhagen requested changes
I have left comments on a) refactoring to do async properly or b) at least moving all async invocations to a single helper method so we only have a single `.Wait()` or `.Result` per flow.

2022-07-14 20:13 UTC, agr commented on src/NuGet.Services.Cursor/NuGet.Services.Cursor.csproj
> +    <TargetFrameworks>net472;netstandard2.1</TargetFrameworks>
Can we just target netstandard2.0 instead? What do we need from 2.1?

2022-07-19 23:53 UTC, joelverhagen commented on src/NuGet.Services.Cursor/NuGet.Services.Cursor.csproj
> +    <TargetFrameworks>net472;netstandard2.1</TargetFrameworks>
Look at the dependencies of https://www.nuget.org/packages/EntityFramework/. This is why it was set as such on NuGetGallery repos.

2022-08-11 06:32 UTC, drewgillies commented on src/NuGet.Services.Storage/AzureStorage.cs
> +                Task.Run(() => _directory.Container.SetPermissionsAsync(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob })).Wait();  // the framework code blocks the
Yes, this was a little excessive - Task.Run will put it on a thread pool thread but that's not necessary here.

2022-08-11 06:32 UTC, drewgillies commented on src/NuGet.Services.Storage/AzureStorage.cs
> +#if NETFRAMEWORK
Yes, good call.

2022-08-11 07:21 UTC, drewgillies commented on src/NuGet.Services.Storage/AzureStorage.cs
> +            if (initializeContainer && _directory.Container.CreateIfNotExistsAsync().Result) // the framework code blocks the thread similarly
We simply can't do this without a significant refactor across the board. For example, this class present `Exists()` and `ExistsAsync()`, overriding methods in the base class `Storage`. This change by necessity turns all flows into async, which is great, but it forces logic like the following into the synchronous method `Exists()`:

```
(await _directory.Value).GetBlockBlobReference(blobName);
```

This is fine/readable/maintainable, but neccesitates an async flow here--we can't access _directory if the caller has requested an initialization via the `initializeContainer` constructor argument, and for it to be anything other than asynchronous access (because initialization is asynchronous). This means `Exists()` needs to return a `Task<bool>` and we can't override the base method due to a different signature. We are essentially breaking an API.

Please let me know if I'm missing something @joelverhagen and @agr (I hope so). I like this approach but if we want to break the API, there will be cost and possibly a bug tail. Which we may also want to embrace.

2022-08-17 05:36 UTC, drewgillies commented
I'm going to close this one for now as I may have a workaround downstream.

2022-08-17 05:36 UTC, closed without merging